export {Home} from "./Home/Home"
export {SingleHotelPage} from "./Single-Hotel-Page/SingleHotelPage"
export {SearchResult} from "./SearchResult/SearchResult"
export {Wishlist} from "./Wishlist/Wishlist"
export {Payment} from "./Payment/Payment"
export {OrderSummary} from "./order-summary/OrderSummary"