export {getHotelsByPrice} from "./PriceRange"
export {getHotelsByRoomsAndBeds} from "./RoomsAndBeds"
export {getHotelsByPropertyType} from "./property-type"
export {getHotelsByRating} from "./Rating"
export {getHotelsByFreeCancel} from "./hotel-cancel"
export {validateName} from "./name-regex"
export {validateEmail} from "./email-regex"
export {validateNumber} from "./number-regex"
export {validatePassword} from "./password-regex"
export { validateConfirmPassword } from "./confirm-password"
export {findHotelInWishlist} from "./find-hotel-in-wishlist"
